---
title: "project_q4"
author: "Dima Mikhaylow"
date: "10/9/2021"
output: html_document
---

```{r}
library(tidyverse)
```



```{r}
df <- read_csv("diamonds4.csv")
head(df)
```


```{r}

ggplot(df, aes(x=carat, y=price))+
  geom_point()+
  geom_smooth(method = "lm", se = TRUE)+
  labs(x="Average body weight", y="Average brain weight",
       title="Regression line with residuals for brain weight against body weight of land mammals")
```

```{r}
result = lm(price ~ carat, data=df)
summary(result)
```


```{r}
y_hat <- result$fitted.values
res <- result$residuals
df <- data.frame(df, y_hat, res)

ggplot(df, aes(x=y_hat, y=res))+
  geom_point()+
  geom_hline(yintercept = 0, color='red')+
  labs(x="Fitted y", y="Residuals", title= "Residual plot before y transformation")
```

```{r}
library(MASS)
boxcox(result)
```


```{r}
acf(res, main="ACF Plot of Residuals with origiinal x")

```

```{r}
y_star<-log(df$price)
df<-data.frame(df,y_star)

result.y_star<-lm(y_star ~ carat, data=df)

y_hat2<-result.y_star$fitted.values
res2<-result.y_star$residuals
df<-data.frame(df,y_hat2,res2)

##residual plot with xstar
ggplot(df, aes(x=y_hat2,y=res2))+
  geom_point()+
  geom_hline(yintercept=0, color="red")+
  labs(x="Fitted y", y="Residuals", title="Residual Plot with xstar")

```


```{r}
y_hat <- result$fitted.values
res <- result$residuals
df <- data.frame(df, y_hat, res)

ggplot(df, aes(x=y_hat, y=res))+
  geom_point()+
  geom_hline(yintercept = 0, color='red')+
  labs(x="Fitted y", y="Residuals", title= "Residual plot before y transformation")
```
```







